#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
HOST = data.get('host')

MESH_HOST = data.get('MESH_HOST', 'https://mesh'+HOST)
MESH_USER = data.get('MESH_USER', 'meshadmin')
MESH_PASS = data.get('MESH_PASS', 'password')
MESH_PERSISTENT_CONFIG = data.get('MESH_PERSISTENT_CONFIG', '0')

mesh_config = {
    'MESH_HOST': MESH_HOST,
    'MESH_USER': MESH_USER,
    'MESH_PASS': MESH_PASS,
    'MESH_PERSISTENT_CONFIG': MESH_PERSISTENT_CONFIG
}
agent.write_envfile("mesh-config.env", mesh_config)

# just before starting systemd unit
#agent.dump_env()
