#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

#This is specific to you module, so you need to change it accordingly.

def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]

# Configure POSTGRES DB

POSTGRES_DB = data.get('POSTGRES_DB', 'docmost')
POSTGRES_USER = data.get('POSTGRES_USER', 'docmost')
POSTGRES_PASSWORD = generate_random_password(16)

posgtres_config = {
    'POSTGRES_DB': POSTGRES_DB,
    'POSTGRES_USER': POSTGRES_USER,
    'POSTGRES_PASSWORD': POSTGRES_PASSWORD
}
agent.write_envfile("database.env", posgtres_config)

MONGO_INITDB_ROOT_USERNAME = data.get('MONGO_INITDB_ROOT_USERNAME', 'tacticalrmm')
MONGO_INITDB_ROOT_PASSWORD = generate_random_password(16)
MONGO_INITDB_DATABASE = data.get('MONGO_INITDB_DATABASE', 'tacticalrmm')

mongo_config = {
    'MONGO_INITDB_ROOT_USERNAME': MONGO_INITDB_ROOT_USERNAME,
    'MONGO_INITDB_ROOT_PASSWORD': MONGO_INITDB_ROOT_PASSWORD,
    'MONGO_INITDB_DATABASE': MONGO_INITDB_DATABASE
}
agent.write_envfile("mongo.env", mongo_config)

# just before starting systemd unit
#agent.dump_env()
